server.port=${PORT:8080}

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://dpg-d7q7clsm0tmc73ctbjag-a:5432/folio2resume
spring.datasource.username=folio2resume_user
spring.datasource.password=R5h519maRSWfJJzi5I2I0qk0PblWsurI
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Mail Configuration (Optional - for contact forms / OTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=folio2resume@gmail.com
spring.mail.password=dfnc alti lemi zsrd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true